name: With TAG

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 2 * * *'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
          git 
          
      - name: Configure SSH
        shell: bash -O extglob {0}
        run: |
          mkdir ~/.ssh/
          echo 'Host aur.archlinux.org
          IdentityFile ~/.ssh/aur
          User aur' >> ~/.ssh/config
        
          echo "${{ secrets.SSH_AUR }}" >  ~/.ssh/aur
          chmod 500 ~/.ssh/aur
          
          ssh-keyscan -t ecdsa aur.archlinux.org,95.216.144.15 > ~/.ssh/known_hosts
          
        
      - name: Version AUR vs GIT
        shell: bash -O extglob {0}
        run: |
          for i in $(cat lista-with-tag); do
            #AUR PKGBUILD
            git clone ssh://aur@aur.archlinux.org/${i}.git -l aur-$i
            cd aur-$i
            source PKGBUILD
            cd ..
            
            #GIT ORIGEN 
            git clone ${url}.git -l git-$i
            cd git-${pkgname}
            vertaggit=$(git tag | sort | tail -n1)
            cd ..
            
            #CHANGE pkgver=
            if [ "${pkgver}" != "${vertaggit}" ]; then
              cd aur-$i
              sed -i "s/pkgver=.*/${vertaggit}/" PKGBUILD
              makepkg --printsrcinfo > .SRCINFO
              git add PKGBUILD .SRCINFO
              git commit -m "version ${vertaggit}"
              git push
            fi
          done
            
      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3 
            
            
